" vim-plug package manager
call plug#begin('~/.vim/plugged')
  Plug 'mattn/emmet-vim'
  Plug 'Yggdroot/indentLine'
  Plug 'chrisbra/vim-commentary'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'sheerun/vim-polyglot'
  Plug 'ghifarit53/tokyonight-vim'
call plug#end()
" hybrid line number
set number relativenumber
" <TAB> equals 2 spaces
set autoindent expandtab tabstop=2 shiftwidth=2
" map CTRL-S to :w<Enter>
nnoremap <C-S> :w<CR>
" load templates
autocmd BufNewFile index.html silent! 0r $HOME/Templates/index.html
autocmd BufNewFile reset.css silent! 0r $HOME/Templates/reset.css
" coc.nvim: use <CR> to confirm completion
inoremap <expr> <cr> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"
" tokyonight colorscheme
set termguicolors
let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1
colorscheme tokyonight
